import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AuthProvider from "./provider";
import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import { Toaster } from "react-hot-toast";

// Fonts
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Metadata (server-only)
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// RootLayout (server component)
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <AuthProvider>
          {/* Navbar and Toaster can be client components */}
          <Navbar />
          <Toaster position="top-right" reverseOrder={false} />
          {children}
        </AuthProvider>
        <Footer />
      </body>
    </html>
  );
}
